// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJyUtn8O9OzddfXfK7Fa3iuI6UzFyUFdU',
    appId: '1:372794944017:web:2bb3b526da86ff0b509fb0',
    messagingSenderId: '372794944017',
    projectId: 'sih-project-4ac7f',
    authDomain: 'sih-project-4ac7f.firebaseapp.com',
    storageBucket: 'sih-project-4ac7f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_ViFOjIk1XLQwu7C9KmVbOBglbtQN7AU',
    appId: '1:372794944017:android:524ab8d5f16ac198509fb0',
    messagingSenderId: '372794944017',
    projectId: 'sih-project-4ac7f',
    storageBucket: 'sih-project-4ac7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX8zkREE1NlK3IUSHVx_cTedTq0UlHvD8',
    appId: '1:372794944017:ios:51430be96b9c7260509fb0',
    messagingSenderId: '372794944017',
    projectId: 'sih-project-4ac7f',
    storageBucket: 'sih-project-4ac7f.firebasestorage.app',
    iosBundleId: 'com.example.sihTimetable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX8zkREE1NlK3IUSHVx_cTedTq0UlHvD8',
    appId: '1:372794944017:ios:51430be96b9c7260509fb0',
    messagingSenderId: '372794944017',
    projectId: 'sih-project-4ac7f',
    storageBucket: 'sih-project-4ac7f.firebasestorage.app',
    iosBundleId: 'com.example.sihTimetable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJyUtn8O9OzddfXfK7Fa3iuI6UzFyUFdU',
    appId: '1:372794944017:web:a30880e0788d37bc509fb0',
    messagingSenderId: '372794944017',
    projectId: 'sih-project-4ac7f',
    authDomain: 'sih-project-4ac7f.firebaseapp.com',
    storageBucket: 'sih-project-4ac7f.firebasestorage.app',
  );
}
